#!/usr/bin/env python3
"""Export the taxonomy-only snapshot consumed by gc-sms.

The "no teaching to the test" boundary (VISION.md § Integrity): gc-sms may
ingest the taxonomy — check ids, names, buckets, severities, scopes, hard-fail
flags — and nothing else. This exporter enforces that boundary by
construction: it emits ONLY the whitelisted fields from checks/<ID>.yaml.
Judge prompts, pass/fail rules, eligibility cues, and scenario text can never
leak into the snapshot because they are never read into the output.

Outputs list-format YAML compatible with gc-sms's parseFailureModesYaml.

Usage:
    uv run python delivery/export_taxonomy_snapshot.py                  # writes delivery/taxonomy-snapshot.yaml
    uv run python delivery/export_taxonomy_snapshot.py --target ../gc-sms/tests/fixtures/invisiblebench-failure-modes.snapshot.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from invisiblebench.evaluation.check_registry import load_checks  # noqa: E402

ALLOWED_FIELDS = ("id", "name", "primary_bucket", "severity", "hard_fail", "scope")
DEFAULT_OUTPUT = REPO_ROOT / "delivery" / "taxonomy-snapshot.yaml"


def build_snapshot() -> str:
    modes, _routing = load_checks()
    lines: list[str] = [
        "# InvisibleBench taxonomy snapshot — generated by",
        "# delivery/export_taxonomy_snapshot.py. Taxonomy fields only;",
        "# regenerate, never hand-edit. Source of truth: checks/<ID>.yaml.",
        "modes:",
    ]
    for check_id in sorted(modes):
        mode = modes[check_id]
        entry = {k: mode[k] for k in ALLOWED_FIELDS if k in mode}
        block = yaml.safe_dump([entry], sort_keys=False, allow_unicode=True)
        lines.append(block.rstrip("\n"))
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target", type=Path, default=DEFAULT_OUTPUT)
    args = ap.parse_args()

    snapshot = build_snapshot()
    args.target.parent.mkdir(parents=True, exist_ok=True)
    args.target.write_text(snapshot, encoding="utf-8")
    count = snapshot.count("- id:")
    print(f"wrote {args.target} ({count} checks, taxonomy fields only)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
