#!/usr/bin/env python3
"""Project the canonical leaderboard into the public web-bench JSON contract.

Near-passthrough projection: reads the safety-care/v1 source artifact, validates
that it already has the lean public shape, and writes the public payload
{schema, notes, scan_metadata, models} to the web-bench target.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_SOURCE = REPO_ROOT / "data" / "leaderboard" / "leaderboard.json"
QA_STAMP_FILENAME = ".qa-stamp"

_PUBLIC_TOP_LEVEL_KEYS = frozenset({"schema", "notes", "scan_metadata", "models"})
_FORBIDDEN_PUBLIC_KEYS = frozenset(
    {
        "_deprecated_v3",
        "overall_leaderboard",
        "overall_score",
        "rank",
        "composite",
        "hard_fail",
        "hard_fail_reasons",
        "primary_bucket",
        "legacy_bucket",
    }
)
_PUBLIC_CLAIM_STATUSES = frozenset({"claim_ready", "not_claim_ready"})


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text())
    if not isinstance(data, dict):
        raise ValueError(f"Expected object JSON at {path}")
    return data


def _generated_at(data: dict[str, Any]) -> str | None:
    scan_meta = data.get("scan_metadata") or {}
    if scan_meta.get("generated_at"):
        return str(scan_meta["generated_at"])
    metadata = data.get("metadata") or {}
    for key in ("scored_at", "generated_at"):
        value = metadata.get(key)
        if value is not None:
            return str(value)
    return None


def _forbidden_key_paths(value: Any, path: str = "") -> list[str]:
    hits: list[str] = []
    if isinstance(value, dict):
        for key, nested in value.items():
            next_path = f"{path}.{key}" if path else str(key)
            if key in _FORBIDDEN_PUBLIC_KEYS:
                hits.append(next_path)
            hits.extend(_forbidden_key_paths(nested, next_path))
    elif isinstance(value, list):
        for idx, nested in enumerate(value):
            hits.extend(_forbidden_key_paths(nested, f"{path}[{idx}]"))
    return hits


@dataclass(frozen=True)
class SyncStatus:
    source: str
    target: str
    source_hash: str
    target_hash: str | None
    source_generated_at: str | None
    target_generated_at: str | None
    in_sync: bool


def project_leaderboard(source: dict[str, Any]) -> dict[str, Any]:
    """Project the canonical safety-care/v1 leaderboard into the public web-bench payload.

    Validates the source, then returns a copy of the lean public contract. The
    source must already be free of retired/private top-level fields; failing here
    makes stale generator output visible instead of silently stripping it.
    """
    schema = source.get("schema")
    if schema != "safety-care/v1":
        raise ValueError(
            f"Expected safety-care/v1 leaderboard artifact, got schema={schema!r}. "
            "Ensure leaderboard.json was generated by the current generate_leaderboard.py."
        )

    extra_keys = sorted(set(source) - _PUBLIC_TOP_LEVEL_KEYS)
    if extra_keys:
        raise ValueError(f"Source leaderboard has non-public top-level keys: {extra_keys}")

    forbidden_paths = _forbidden_key_paths(source)
    if forbidden_paths:
        raise ValueError(f"Source leaderboard has forbidden public key(s): {forbidden_paths}")

    models = source.get("models")
    if not isinstance(models, list) or len(models) == 0:
        raise ValueError("Source leaderboard missing or empty models[]")

    for entry in models:
        model_name = entry.get("model") or "<unknown>"
        if "safety" not in entry:
            raise ValueError(f"Model {model_name!r} is missing required 'safety' key")
        if "care" not in entry:
            raise ValueError(f"Model {model_name!r} is missing required 'care' key")
        _validate_care_claim_statuses(entry, str(model_name))

    return {key: source[key] for key in ("schema", "notes", "scan_metadata", "models")}


def _validate_care_claim_statuses(entry: dict[str, Any], model_name: str) -> None:
    qualities = ((entry.get("care") or {}).get("qualities") or {})
    if not isinstance(qualities, dict):
        raise ValueError(f"Model {model_name!r} care.qualities missing or not an object")

    for quality, quality_data in qualities.items():
        if not isinstance(quality_data, dict):
            raise ValueError(f"Model {model_name!r} care quality {quality!r} is not an object")
        if "status" in quality_data:
            raise ValueError(
                f"Model {model_name!r} care quality {quality!r} uses retired status key"
            )
        claim_status = quality_data.get("calibration_status")
        if claim_status not in _PUBLIC_CLAIM_STATUSES:
            raise ValueError(
                f"Model {model_name!r} care quality {quality!r} has invalid "
                f"calibration_status={claim_status!r}"
            )


def _projected_bytes(source: Path) -> bytes:
    projected = project_leaderboard(_read_json(source))
    return json.dumps(projected, indent=2, sort_keys=True).encode() + b"\n"


def compute_sync_status(source: Path, target: Path) -> SyncStatus:
    if not source.exists():
        raise FileNotFoundError(f"Source leaderboard not found: {source}")

    source_data = _read_json(source)
    projected = json.dumps(project_leaderboard(source_data), indent=2, sort_keys=True).encode() + b"\n"
    target_data = _read_json(target) if target.exists() else {}
    target_bytes = target.read_bytes() if target.exists() else None
    return SyncStatus(
        source=str(source),
        target=str(target),
        source_hash=_sha256_bytes(projected),
        target_hash=_sha256_bytes(target_bytes) if target_bytes is not None else None,
        source_generated_at=_generated_at(source_data),
        target_generated_at=_generated_at(target_data) if target.exists() else None,
        in_sync=target_bytes == projected,
    )


class QAStampError(RuntimeError):
    """The source leaderboard has no fresh strict-QA stamp — refuse to write.

    VISION.md: no side doors. publish.py (the fail-closed generate -> strict
    QA -> sync chain) writes this stamp immediately after strict QA passes;
    calling this script directly on a leaderboard.json that was never QA'd
    (or was regenerated/hand-edited since it last was) must fail loudly
    instead of silently shipping unvetted content to a public target.
    """


def _qa_stamp_path(source: Path) -> Path:
    return source.parent / QA_STAMP_FILENAME


def _verify_qa_stamp(source: Path) -> None:
    stamp_path = _qa_stamp_path(source)
    if not stamp_path.exists():
        raise QAStampError(
            f"No QA stamp at {stamp_path}. Run the fail-closed publish chain "
            "(scripts/publish.sh or `python -m invisiblebench.publish`) instead of "
            "calling sync_web_bench.py directly, or pass --unsafe-debug-bypass for "
            "a deliberate debug write."
        )

    try:
        stamp = json.loads(stamp_path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        raise QAStampError(f"QA stamp at {stamp_path} is unreadable: {exc}") from exc

    actual_hash = _sha256_bytes(source.read_bytes())
    if stamp.get("leaderboard_sha256") != actual_hash:
        raise QAStampError(
            f"QA stamp at {stamp_path} is stale — {source} changed since strict QA "
            "last passed against it (content hash mismatch). Re-run the publish "
            "chain, or pass --unsafe-debug-bypass for a deliberate debug write."
        )


def _print_unsafe_bypass_warning(source: Path, target: Path) -> None:
    print(
        "\n".join(
            [
                "=" * 72,
                "UNSAFE DEBUG BYPASS — writing web-bench payload with NO fresh QA stamp.",
                f"  source: {source}",
                f"  target: {target}",
                "This skips the fail-closed publish gate (VISION.md: no side doors).",
                "Never use --unsafe-debug-bypass for a real publish — debugging only.",
                "=" * 72,
            ]
        ),
        file=sys.stderr,
    )


def sync_leaderboard(source: Path, target: Path, *, unsafe_debug_bypass: bool = False) -> SyncStatus:
    status = compute_sync_status(source, target)
    if status.in_sync:
        return status

    if unsafe_debug_bypass:
        _print_unsafe_bypass_warning(source, target)
    else:
        _verify_qa_stamp(source)

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(_projected_bytes(source))
    return compute_sync_status(source, target)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Project leaderboard JSON into web-bench public assets"
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help=f"Source leaderboard artifact (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument("--target", type=Path, required=True, help="web-bench public leaderboard path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the target differs instead of writing the projection",
    )
    parser.add_argument(
        "--unsafe-debug-bypass",
        action="store_true",
        help=(
            "Skip the QA-stamp freshness gate and write anyway. Debugging only — "
            "never for a real publish (VISION.md: no side doors)."
        ),
    )
    args = parser.parse_args(argv)

    status = compute_sync_status(args.source, args.target)
    if args.check:
        print(json.dumps({"status": "ok" if status.in_sync else "drift", "data": asdict(status)}, indent=2))
        return 0 if status.in_sync else 1

    try:
        synced = sync_leaderboard(args.source, args.target, unsafe_debug_bypass=args.unsafe_debug_bypass)
    except QAStampError as exc:
        print(json.dumps({"status": "error", "error": str(exc)}, indent=2), file=sys.stderr)
        return 1

    print(json.dumps({"status": "synced", "data": asdict(synced)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
