#!/usr/bin/env python3
"""Project the canonical leaderboard into the public web-bench JSON contract.

Near-passthrough projection: reads the safety-care/v1 source artifact, validates
it, strips private/deprecated keys (_deprecated_v3), and writes the public payload
{schema, notes, scan_metadata, models} to the web-bench target.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_SOURCE = REPO_ROOT / "data" / "leaderboard" / "leaderboard.json"

# Keys that must never appear in the public payload.
_PRIVATE_KEYS = frozenset({"_deprecated_v3"})


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text())
    if not isinstance(data, dict):
        raise ValueError(f"Expected object JSON at {path}")
    return data


def _generated_at(data: dict[str, Any]) -> str | None:
    scan_meta = data.get("scan_metadata") or {}
    if scan_meta.get("generated_at"):
        return str(scan_meta["generated_at"])
    metadata = data.get("metadata") or {}
    for key in ("scored_at", "generated_at"):
        value = metadata.get(key)
        if value is not None:
            return str(value)
    return None


@dataclass(frozen=True)
class SyncStatus:
    source: str
    target: str
    source_hash: str
    target_hash: str | None
    source_generated_at: str | None
    target_generated_at: str | None
    in_sync: bool


def project_leaderboard(source: dict[str, Any]) -> dict[str, Any]:
    """Project the canonical safety-care/v1 leaderboard into the public web-bench payload.

    Validates the source, then returns a copy with all private/deprecated keys
    stripped.  The public contract is {schema, notes, scan_metadata, models}.
    """
    schema = source.get("schema")
    if schema != "safety-care/v1":
        raise ValueError(
            f"Expected safety-care/v1 leaderboard artifact, got schema={schema!r}. "
            "Ensure leaderboard.json was generated by the current generate_leaderboard.py."
        )

    models = source.get("models")
    if not isinstance(models, list) or len(models) == 0:
        raise ValueError("Source leaderboard missing or empty models[]")

    for entry in models:
        model_name = entry.get("model") or "<unknown>"
        if "safety" not in entry:
            raise ValueError(f"Model {model_name!r} is missing required 'safety' key")
        if "care" not in entry:
            raise ValueError(f"Model {model_name!r} is missing required 'care' key")

    # Build the public payload: all top-level keys except private ones.
    public: dict[str, Any] = {
        k: v for k, v in source.items() if k not in _PRIVATE_KEYS
    }
    return public


def _projected_bytes(source: Path) -> bytes:
    projected = project_leaderboard(_read_json(source))
    return json.dumps(projected, indent=2, sort_keys=True).encode() + b"\n"


def compute_sync_status(source: Path, target: Path) -> SyncStatus:
    if not source.exists():
        raise FileNotFoundError(f"Source leaderboard not found: {source}")

    source_data = _read_json(source)
    projected = json.dumps(project_leaderboard(source_data), indent=2, sort_keys=True).encode() + b"\n"
    target_data = _read_json(target) if target.exists() else {}
    target_bytes = target.read_bytes() if target.exists() else None
    return SyncStatus(
        source=str(source),
        target=str(target),
        source_hash=_sha256_bytes(projected),
        target_hash=_sha256_bytes(target_bytes) if target_bytes is not None else None,
        source_generated_at=_generated_at(source_data),
        target_generated_at=_generated_at(target_data) if target.exists() else None,
        in_sync=target_bytes == projected,
    )


def sync_leaderboard(source: Path, target: Path) -> SyncStatus:
    status = compute_sync_status(source, target)
    if status.in_sync:
        return status

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(_projected_bytes(source))
    return compute_sync_status(source, target)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Project leaderboard JSON into web-bench public assets"
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help=f"Source leaderboard artifact (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument("--target", type=Path, required=True, help="web-bench public leaderboard path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the target differs instead of writing the projection",
    )
    args = parser.parse_args()

    status = compute_sync_status(args.source, args.target)
    if args.check:
        print(json.dumps({"status": "ok" if status.in_sync else "drift", "data": asdict(status)}, indent=2))
        return 0 if status.in_sync else 1

    synced = sync_leaderboard(args.source, args.target)
    print(json.dumps({"status": "synced", "data": asdict(synced)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
